spring.config.import=optional:file:.env[.properties]

spring.application.name=projetotcc

spring.jpa.database=POSTGRESQL
spring.datasource.plataform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/figura
spring.datasource.username=admin
spring.datasource.password=admin

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true