spring.config.import=optional:file:.env[.properties]

spring.application.name=projetotcc

spring.jpa.database=POSTGRESQL
spring.datasource.plataform=postgres
spring.datasource.url=jdbc:postgresql://dpg-csbatqdumphs73b9v2rg-a.oregon-postgres.render.com:5432/matracadata
spring.datasource.username=matracadata_user
spring.datasource.password=L0PWHvVuMxPkAxQSlOwy3mBjODQ5kd8O
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true